### ISSUE TITLE
na_ontap_ports Not removing ports from broadcast domains

### ISSUE THREAD

**Issue by rhinson-bw** [ansible-collections/netapp.ontap#84] opened 2022-07-14 00:28 UTC
Hello, 

Running into an issue with the `na_ontap_ports` module where we are not able to remove a port from a broadcast domain. 

After some troubleshooting, we found that the ZAPI method in `na_ontap_broadcast_domain_ports` module works fine (I am  assuming it works with the conversion from `names` to `ports` in the `na_ontap_ports` module).

Looking more at the `remove_broadcast_domain_ports_rest` function in `na_ontap_ports`, we found that the `api = "private/cli/network/port/broadcast-domain/remove-ports"` does not match up with the current REST documentation
https://github.com/ansible-collections/netapp.ontap/blob/bb287efb507ef227f3df59fe7a9839126b455592/plugins/modules/na_ontap_ports.py#L260-L266

9.6-9.11 REST Documentation suggests `/network/ethernet/ports/{uuid}` is the object and method associated with removing a port from a broadcast domain: 

> PATCH
[/network/ethernet/ports/{uuid}](https://library.netapp.com/ecmdocs/ECMLP2856304/html/index.html#/networking/network_ethernet_port_modify)

>Updates a port.

>Related ONTAP commands
>network port broadcast-domain add-ports
>_**network port broadcast-domain remove-ports**_
>network port ifgrp modify
>network port modify
>network port vlan modify

However, there doesn't seem to be any equivalent functionality in `/network/ethernet/ports/{uuid}` with what was proposed in the code block or REST documentation. 

Please let me know if I am missing something here - the `na_ontap_broadcast_domain_ports` is working for now, but would like to be able to do this with REST.

**Comment by lonico** [comment] 2022-07-14 02:54
During our testing, we found out that we could not use PATCH /network/ethernet/ports/{uuid} to only remove a port.   It would only allow to move a port, as also indicated in the documentation:
```
The following PATCH request removes the port from the current broadcast domain and adds it to the specified broadcast domain.
```

This is why we resorted to private/cli, which invokes the ONTAP CLI under the cover.

Now the question is why this API call is failing to remove the port on your system.  Are you seeing some kind of error?   If not, you could trace the API call and see the response:
https://github.com/ansible-collections/netapp.ontap/wiki/Debugging/_edit#tracing-zapi-and-rest-api-calls

**Comment by carchi8py** [comment] 2022-08-02 21:36
@rhinson-bw could you let us know what the issue is, or if you having an issue. I'll close this story for now, if there is an issue reopen.

**Closed by carchi8py** 2022-08-02 21:36 UTC
